points:
  position:
    x: -1.9999998807907104
    y: -0.39999985694885254
  position:
    x: -1.9715254540968772
    y: -0.4179205420303447
  position:
    x: -1.9733458276591591
    y: -0.3929869173912266
  position:
    x: -1.9858908412738288
    y: -0.3713621612096176
  position:
    x: -1.9878554103949
    y: -0.34643921772300246
  position:
    x: -1.9902449367976942
    y: -0.3215536582701475
  position:
    x: -1.9913946865706862
    y: -0.29658036077887573
  position:
    x: -1.9926604031422812
    y: -0.27161240386385543
  position:
    x: -1.9934881924612569
    y: -0.2466261364016873
  position:
    x: -1.9943793057557855
    y: -0.22164215775791263
  position:
    x: -1.9950812100631197
    y: -0.19665207559842202
  position:
    x: -1.995838808951362
    y: -0.1716635193178604
  position:
    x: -1.9965155362563678
    y: -0.14667267421890529
  position:
    x: -1.9972502469606752
    y: -0.12168335499887917
  position:
    x: -1.9979605436021188
    y: -0.09669327283938856
  position:
    x: -1.99873492715858
    y: -0.07170547949829142
  position:
    x: -1.999516940109686
    y: -0.046717686157194294
  position:
    x: -2.00036990643099
    y: -0.021732181634490644
  position:
    x: -2.001252627391409
    y: 0.0032517970092840187
  position:
    x: -2.002212405237742
    y: 0.0282334868346652
  position:
    x: -2.0032156706335513
    y: 0.053213650781117394
  position:
    x: -2.004301333491526
    y: 0.07819000003024712
  position:
    x: -2.005441927990944
    y: 0.10316406046098336
  position:
    x: -2.0066694975893142
    y: 0.12813354325493265
  position:
    x: -2.0079588652843086
    y: 0.15310073723048845
  position:
    x: -2.009339785715042
    y: 0.1780625906297928
  position:
    x: -2.0107886077581156
    y: 0.20302062933177467
  position:
    x: -2.0123320342947864
    y: 0.2279725645180406
  position:
    x: -2.0139487030200485
    y: 0.25292068500698406
  position:
    x: -2.015661502117837
    y: 0.2778611761012826
  position:
    x: -2.0053267241318053
    y: 0.3006250009033806
  position:
    x: -1.9997755765881493
    y: 0.3250009167939538
  position:
    x: -1.9999998807907104
    y: 0.35000015422701836
  position:
    x: -1.9999998807907104
    y: 0.4000001549720764
  position:
    x: -1.9999998807907104
    y: 0.4500001557171345
  position:
    x: -2.0
    y: 0.5